language: php

php:
  - "7.2"
  - "7.3"
  - "7.4"

env:
  global: 
    - LARAVEL_DEV_RELEASE='^7.0'
  matrix:
    - LARAVEL='5.6.*'
    - LARAVEL='5.6.*' COMPOSER_FLAGS="--prefer-lowest"
    - LARAVEL='5.7.*'
    - LARAVEL='5.7.*' COMPOSER_FLAGS="--prefer-lowest"
    - LARAVEL='5.8.*'
    - LARAVEL='5.8.*' COMPOSER_FLAGS="--prefer-lowest"
    - LARAVEL='^6.0'
    - LARAVEL='^6.0' COMPOSER_FLAGS="--prefer-lowest"
    - LARAVEL='^7.0'
    - LARAVEL='^7.0' COMPOSER_FLAGS="--prefer-lowest"

install:
  - if [ $LARAVEL == $LARAVEL_DEV_RELEASE ]; then composer config minimum-stability dev; fi
  - composer require "illuminate/contracts:${LARAVEL}" --prefer-dist --no-interaction --no-suggest
  - composer install --prefer-dist --no-interaction --no-suggest

script:
  - vendor/bin/phpunit

cache:
  directories:
    - $HOME/.composer/cache
